version: '3.1'
services:
  postgresDB:
    image: postgres:latest
    secrets:
      - db_username
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_username

  centOS:
    image: centos
    deploy:
      replicas: 1  
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    secrets:
      - source: my-secret

secrets:
  db_username:
    file: ./postgres_user.txt
  db_password:
    file: ./postgres_password.txt     # requires these files in the local directory as the yml file.
  my-secret: 
    external: true     # requires a secret of this name already created manually.