version: "3.1"
services:
  mysqlDB:
    image: mysql:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.name == andis
    environment:
      - MYSQL_ROOT_PASSWORD="mypass"
      - MYSQL_DATABASE="mydb"